### PR TITLE
fix alarms.db.url-when-type-is-rdbms

### PR DESCRIPTION
**Pull request by alrossi**
(immutable)alarms.db.url-when-type-is-rdbms=jdbc:${alarms.db.rdbms.type}://${alarms.db.host}/${alarms.db.name}

to

(immutable)alarms.db.url-when-type-is-rdbms=jdbc:${alarms.db.type}://${alarms.db.host}/${alarms.db.name}

### CODE REVIEW

**Comment by alrossi** [comment]
I've double-checked.  This should fix the database problem.   You should just set:

[alarmsDomain]
[alarmsDomain/alarms]
alarms.enable.email=true
alarms.email.threshold=high
alarms.email.smtp-host=ex-smtp.fnal.gov
alarms.email.to=dcache-auto@fnal.gov
alarms.email.from=dmsdca07.fnal.gov
alarms.db.host=fndcatemp2.fnal.gov
alarms.db.type=rdbms

Maybe adjust the threshold for email, or modify the actual level settings using the alarms admin commands

priority set <alarm type> LOW|MODERATE|HIGH|CRITICAL

and then

priority save

**Comment by DmitryLitvintsev** [comment]
the situation is more fishy. 
I fixed it myself along the lines of your patch here:

diff --git a/skel/share/defaults/alarms.properties b/skel/share/defaults/alarms.properties
index c5a147199d..5e8cb851aa 100644
--- a/skel/share/defaults/alarms.properties
+++ b/skel/share/defaults/alarms.properties
@@ -243,7 +243,7 @@ alarms.plugin!alarms=${alarms.dir}
 #
 (immutable)alarms.db.url-when-type-is-off=off
 (immutable)alarms.db.url-when-type-is-xml=xml:file:${alarms.db.xml.path}
-(immutable)alarms.db.url-when-type-is-rdbms=jdbc:${alarms.db.rdbms.type}://${alarms.db.host}/${alarms.db.name}
+(immutable)alarms.db.url-when-type-is-rdbms=jdbc:${alarms.db.type}://${alarms.db.host}/${alarms.db.name}
 alarms.db.url=${alarms.db.url-when-type-is-${alarms.db.type}}
 
re-installed and got this exception:

25 Aug 2017 16:07:39 (alarms) [] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logEntryHandler' defined in class path resource [org/dcache/alarms/logback/alarms.xml]: Cannot resolve reference to bean 'alarmStore' while setting bean property 'store'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alarmStore' defined in class path resource [org/dcache/alarms/logback/alarms.xml]: Cannot resolve reference to bean 'pmf' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pmf' defined in class path resource [org/dcache/alarms/logback/alarms.xml]: Cannot resolve reference to bean 'dataSource' while setting bean property 'connectionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/dcache/alarms/logback/alarms.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Constructor threw exception; nested exception is java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:rdbms://dmsdca07.fnal.gov/alarms

Indeed, the JDBC URL CANNOT BE:

jdbc:rdbms://dmsdca07.fnal.gov

it can't be "rdbms" (can be postgresql or oracle or mysql):

So I set 

alarms.db.url=jdbc:postgresql://${billing.db.host}/${alarms.db.name}

in /etc/dcache/dcache.conf 

and it works now 

So this needs to be rectified.

**Comment by alrossi** [comment]
Ah, yes, now I remember.  That's what the rdbms type was for.

alarms.db.rdbms=postgresql

So let me redo this

**Comment by alrossi** [comment]
That's why that property disappeared.  We just hard-coded it as postgresql

**Comment by alrossi** [comment]
Excuse me.  Gerd, not Paul:

8ea811d5768 (Gerd Behrmann            2014-07-22 11:15:33 +0200 251) (immutable)alarms.db.url-when-type-is-xml=xml:file:${alarms.db.xml.path}
b43a7059fac (Gerd Behrmann            2016-08-16 21:54:56 +0200 252) (immutable)alarms.db.url-when-type-is-rdbms=jdbc:postgresql://${alarms.db.host}/${alarms.db.name}?targetServerType=master
8ea811d5768 (Gerd Behrmann            2014-07-22 11:15:33 +0200 253) alarms.db.url=${alarms.db.url-when-type-is-${alarms.db.type}}

**Pull request closed without merging**
